[package]
name = "ulanzi"
version = "0.1.0"
license.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = ["time", "random"] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }
embassy-time = { workspace = true }
embassy-sync = { workspace = true }
smart-leds = "0.4.0"
smart-leds-trait = "0.3.1"
esp-hal.workspace = true
#esp-hal-smartled = { version = "0.17.0", features = ["esp32", "defmt"] }
esp-hal-smartled = { git = "https://github.com/kaspar030/esp-hal-community", branch = "fix-smartled-with-esp_hal-1.0.0", features = [
  "defmt",
  # … and any of esp32 or esp32s3 or future others will be enabled by smartled-config through the local laze.yml.
] }
embassy-executor = { workspace = true, default-features = false }
embedded-graphics-core = "0.4.0"
embedded-graphics = "0.8.1"
rand_core.workspace = true
cfg-if.workspace = true
coap-handler-implementations = "0.6.2"
minicbor = "2.2.1"
coap-message-utils = "0.3.9"
heapless.workspace = true
minicbor-adapters = "0.0.8"
itertools = { version = "0.14.0", default-features = false }
embassy-futures.workspace = true
critical-section.workspace = true

# Needed for the S3 Matrix; workaround for <https://github.com/ariel-os/ariel-os/issues/1949>
embassy-time-queue-utils = { version = "*", features = ["_generic-queue"] }
